<?php

/* COPYRIGHT (C) HARRY CLARK 2024 */
/* GENERIC ALL PURPOSE PHP PASSWORD GENERATOR */

/* THE FOLLOWING FILE PERTAINS TOWARDS THE FUNCTIONALITY OF USING 
PHP'S BUILT-IN CYRPTOGRAPHIC FUNCTIONS, REJECTION SAMPLING TO REMOVE RANDOM BIAS
(CON-CURRENT CREATIONS OF THE SAME HASH BASED ON THE SAME CHAR'S)

AMONG OTHER PRE-REQUISITES THAT WILL MAKE THIS UTILITY A VERSATILE ALTERNATIVE
*/

/* PRE-PROCESSOR DIRECTIVES */

define('MAX_PASSWORD_LEN', 128);
define('MIN_PASSWORD_LEN', 12);
define('MULTI', 2);

class Password implements password_impl
{
    public function GET_SECURE_BYTES($LEN) { return random_bytes($LEN); }
}

?>
